version: '3'

services:
  admin:
    build: 
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./admin/.env
    ports:
      - "3001:3001"

  robot:
    build: 
      context: ./robot
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./robot/.env
    ports:
      - "3000:3000"
