# Nome da ação
name: Deploy Docusaurus

# Abaixo definimos quando a ação deve ser executada
on:
  push:
    branches:
      - main

# Define as permissões do GITHUB_TOKEN para permitir a implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação concorrente
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Os runners hospedados pelo GitHub têm 7 GB de memória disponíveis, vamos usar 6 GB
  NODE_OPTIONS: --max-old-space-size=6144

# Os passos representam uma sequência de tarefas que serão executadas como parte do trabalho
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        ref: "main"  # Define a branch de destino como "main"

    - name: Configuração do Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Instalação e Construção
      run: |
        cd docs
        npm install
        npm run build
        mv build ../build
        
    - name: Configuração das Páginas
      uses: actions/configure-pages@v3
        
    - name: Upload do artefato
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./build

    - name: Implantação no GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
